infrastructure:
  - "*.tf"
  - "**/*.tf"

ci/cd:
  - ".github/workflows/*"
  - ".github/workflows/**/*.yml"
  - ".github/workflows/**/*.yaml"

documentation:
  - "**/*.md"

scripts:
  - "**/*.sh"
  - "**/*.ps1"
  - "**/*.psm1"

configs:
  - "config/*.yml"
  - "config/*.yaml"
  - "config/*.json"


python:
  - "**/*.py"

tests:
  - "**/tests/*.py"
  - "**/test_*.py"
  - "**/tests/**/*.py"
  - "**/test_*.py"

