name: "Label PRs"

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      # The labeler action requires write permissions to label pull requests
      # This is necessary for the labeler action to function correctly
      pull-requests: write
    steps:
      - id: labeler
        uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: ".github/labeler.yml"