name: "Label PRs"

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - id: labeler
        uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
    permissions:
      contents: read
      pull-requests: write
      # issues: write
      # statuses: write
      # checks: write
      # actions: write
      # deployments: write