# Public automatoin engine where we can run terraform commands

name: Terraform CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    terraform:
        name: Validate Terraform Code
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
    
            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                terraform_version: 1.6.6

            - name: Terraform Format Check
              run: terraform fmt -check -recursive
        
            - name: Terraform Init
              run: terraform init
        
            # - name: Terraform Plan
            #   run: terraform plan -out=tfplan
        
            # - name: Terraform Apply
            #   run: terraform apply -auto-approve
            
            # - name: Terraform Destroy
            #   run: terraform destroy -auto-approve

            - name: Terraform Output
              run: terraform output
            
            - name: Terraform Format
              run: terraform fmt -check
            
            - name: Terraform Validate
              run: terraform validate


# Every push to the main branch will trigger this workflow
# The workflow will run on the latest version of Ubuntu
#If formatting is not correct, it will fail the workflow